SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('webhooks/', include('webhooks.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from accounts.forms import RegisterForm
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    RegisterView,
    DashboardView,
    FacebookLoginView,
    FacebookProfileView,
    AddPost,
    AutomatedResponsesView,
    FacebookMorePosts,
    FacebookSearchPostsView,
    FacebookScheduledPostsView,
    FacebookLifeTimePostsView,
    FacebookPublishedPostsView,
    ReplyView,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name= 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('facebook-login/', FacebookLoginView.as_view(), name='facebook-login'),
    path('facebook/posts', FacebookProfileView.as_view(), name='facebook-profile'),
    path('facebook/more-posts', FacebookMorePosts.as_view(), name='facebook-more-posts'),
    path('facebook/scheduled-posts', FacebookScheduledPostsView.as_view(), name='facebook-scheduled-posts'),
    path('facebook/published-posts', FacebookPublishedPostsView.as_view(), name='facebook-published-posts'),
    path('facebook/posts/<str:lifetime>', FacebookLifeTimePostsView.as_view(), name = 'facebook-posts-lifetime'),
    path('add-post/', AddPost.as_view(), name='add-post'),
    path('add-automate-response/<str:post_id>/', AutomatedResponsesView.as_view(), name='response'),
    path('facebook/search-post/<str:post_id>', FacebookSearchPostsView.as_view() ,name='search-post'),
    path('facebook/post/reply', ReplyView.as_view(), name='reply'),
]

main/urls.py
from os import name
from django.urls import path
from .views import HomeView


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
    class Meta():
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )
        widgets = {
            'email'         : forms.TextInput(attrs={'class': 'form-control'}),
            'first_name'    : forms.TextInput(attrs={'class': 'form-control'}),
            'last_name'     : forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib import messages
from django.http import response
from django.utils.html import escape
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView
from django.views.generic.base import View
import requests
from . import functions
from calendar import monthrange
from datetime import date, datetime, time
from requests.api import delete, post, request
from requests.sessions import Request
from .models import User
from .forms import RegisterForm
from .facebookapi import FacebookGraph
from .models import (
    UserProfile,
    FacebookApp,
    FacebookPage,
    AutomatedResponses,
)


class RegisterView(SuccessMessageMixin, CreateView):
    model = User
    form_class = RegisterForm
    success_url = '/accounts/login'
    template_name = 'accounts/register.html'
    context_object_name = 'form'
    success_message = 'Your account created successfully!'


class DashboardView(LoginRequiredMixin, View):
    template_name = 'accounts/dashboard.html'
    def get(self, request, *args, **kwargs):
        try:
            profile = UserProfile.objects.get(user = request.user) 
        except:
            profile = UserProfile.objects.create(user = request.user)
        
        # page = profile.facebookpage_set.first()
        # try:
        #     page_id = request.session['page_id']
        # except:
            # page_id = request.session.get('page_id', page.id)

        data = {'profile': profile, 'pages': profile.facebookpage_set.all()}
        return render(request, self.template_name,  data)

class FacebookLoginView(LoginRequiredMixin, View):
    try:
        app = FacebookApp.objects.first()
        app_id = app.app_id
        app_secret = app.app_secret
        redirect_url = app.redirect_url
    except:
        app_id = '482847369816069'
        app_secret = '11b994aa0b08dabbcb04c3b2ade775e7'
        redirect_url = 'https://mhddaghestani.pythonanywhere.com/accounts/facebook-login/'
    def get(self, request, *args, **kwargs):
        # if request.user.is_authenticated:
        try:
            profile = UserProfile.objects.get(user = request.user) 
        except:
            profile = UserProfile.objects.create(user = request.user)
        graph = FacebookGraph(self.app_id, self.app_secret, self.redirect_url)
        
        try:
            profile.facebook_user_code = request.GET['code']
            info = graph.get_user_access_token(request.GET['code'])
            profile.facebook_user_access_token = info['access_token']
            profile.facebook_user_id = info['id']
            profile.facebook_user_name = graph.get_user_name()
            profile.pic_url = graph.get_user_profile_picture()
            profile.save()
            for key, value in graph.get_pages().items():
                try:
                    FacebookPage.objects.get(id = value['id'],)
                except:    
                    page = FacebookPage.objects.create(user_profile = profile, id = value['id'], access_token = value['access_token'], name = value['name'])
                    page.pic_url = graph.picture_url(value['id'], value['access_token'])
                    page.save()
            messages.success(request, 'You signed into facebook successfuly!')
            return HttpResponseRedirect(reverse('accounts:dashboard'))
        except:
            messages.success(request, 'Error signing to facebook, Please try again')
            return HttpResponseRedirect(reverse('accounts:dashboard'))
                    
        # context = request.GET['code']
        # return render(request, 'accounts/facebook-info.html', {'data': context})

class FacebookProfileView(LoginRequiredMixin,View):
    template_name   = 'accounts/facebook-dashboard.html'
    no_pages        = 'accounts/no-pages.html'
    no_account      = 'accounts/no-account.html'
    try:
        app = FacebookApp.objects.first()
        app_id = app.app_id
        app_secret = app.app_secret
        redirect_url = app.redirect_url
    except:
        app_id = '482847369816069'
        app_secret = '11b994aa0b08dabbcb04c3b2ade775e7'
        redirect_url = 'https://mhddaghestani.pythonanywhere.com/accounts/facebook-login/'
    def get(self, request, *args, **kwargs):
        try:
            profile = UserProfile.objects.get(user = request.user) 
        except:
            profile = UserProfile.objects.create(user = request.user)

        if profile.facebookpage_set.all().count() == 0: 
            if  not profile.facebook_user_id == None:
                return render(request, self.no_pages)
            else:
                return render(request, self.no_account)
        
        # try:
        #     print(request.GET['posts'])
        # except:
        #     print(None)
        page_id = functions.get_page_id(request, profile)
        if not page_id == '':
            graph = FacebookGraph(self.app_id, self.app_secret, self.redirect_url)
            page = request.user.userprofile.facebookpage_set.get(id = page_id)
            graph.access_token = page.access_token
            pic_url = graph.picture_url(page.id, page.access_token)
            posts = graph.get_posts()
            request.session['next_paging'] = ''
            request.session['next_paging'] = graph.next_paging
            # print(request.session['next_paging'])
            return render(request, self.template_name, {'profile': profile, 'pages': profile.facebookpage_set.all(), 'page_id': page_id, 'posts': posts, 'page': page, 'pic_url': pic_url, 'next': request.session['next_paging'] if request.session['next_paging'] != None else False})
        return render(request, self.template_name, {'profile': profile})

class FacebookMorePosts(View):
    template_name = 'accounts/posts.html'
    try:
        app = FacebookApp.objects.first()
        app_id = app.app_id
        app_secret = app.app_secret
        redirect_url = app.redirect_url
    except:
        app_id = '482847369816069'
        app_secret = '11b994aa0b08dabbcb04c3b2ade775e7'
        redirect_url = 'https://mhddaghestani.pythonanywhere.com/accounts/facebook-login/'
    def get(self, request, *args, **kwargs):
        url = request.session['next_paging']
        if url == '':
            profile = UserProfile.objects.get(user = request.user) 
            page_id = functions.get_page_id(request, profile)
            page = request.user.userprofile.facebookpage_set.get(id = page_id)
            graph = FacebookGraph(self.app_id, self.app_secret, self.redirect_url)
            graph.access_token = page.access_token
            posts = graph.get_posts()
            request.session['next_paging'] = graph.next_paging
            return render(request, self.template_name, {'posts': posts})

        if url != None:
            req = requests.get(url)
            data = req.json()['data']
            for post in data:
                post['created_time'] = datetime.strptime(post['created_time'], "%Y-%m-%dT%H:%M:%S%z") 
            try:
                request.session['next_paging'] = req.json()['paging']['next']
            except:
                request.session['next_paging'] = None
            return render(request, self.template_name, {'posts': data})
        else:
            return HttpResponse('None')

class FacebookSearchPostsView(View):
    template_name = 'accounts/post.html'
    try:
        app = FacebookApp.objects.first()
        app_id = app.app_id
        app_secret = app.app_secret
        redirect_url = app.redirect_url
    except:
        app_id = '482847369816069'
        app_secret = '11b994aa0b08dabbcb04c3b2ade775e7'
        redirect_url = 'https://mhddaghestani.pythonanywhere.com/accounts/facebook-login/'
    def get(self, request, post_id, *args, **kwargs):
        request.session['next_paging'] = ''
        graph = FacebookGraph(self.app_id, self.app_secret, self.redirect_url)
        profile = UserProfile.objects.get(user = request.user) 
        page_id = functions.get_page_id(request, profile)
        if not page_id == '':
            page = request.user.userprofile.facebookpage_set.get(id = page_id)
            graph.access_token = page.access_token
            post_id = page_id + '_' + post_id
            try:
                post = graph.get_post_details(post_id)
                scheduled = str(datetime.now()) < str(post['created_time'])
                # print(str(datetime(2021, 8, 28, 1, 56, 0)) > str(post['created_time']))
                return render(request, self.template_name, {'post': post, 'scheduled': scheduled})
            except:
                return HttpResponse("noResults")
        return HttpResponse("pageError")


class FacebookScheduledPostsView(View):
    posts_template_name = 'accounts/posts.html'
    post_template_name = 'accounts/post.html'
    try:
        app = FacebookApp.objects.first()
        app_id = app.app_id
        app_secret = app.app_secret
        redirect_url = app.redirect_url
    except:
        app_id = '482847369816069'
        app_secret = '11b994aa0b08dabbcb04c3b2ade775e7'
        redirect_url = 'https://mhddaghestani.pythonanywhere.com/accounts/facebook-login/'
    def get(self, request, *args, **kwargs):
        request.session['next_paging'] = ''
        profile = UserProfile.objects.get(user = request.user) 
        page_id = functions.get_page_id(request, profile)
        page = request.user.userprofile.facebookpage_set.get(id = page_id)
        graph = FacebookGraph(self.app_id, self.app_secret, self.redirect_url)
        graph.access_token = page.access_token

templates/accounts/add_post.html
{% extends 'main/base.html' %}
{% block content %}
<br><br><br><br>
<form action="" method="post">
{% csrf_token %}
<div>
    <select name="page_id" id="">
        {% for page in pages %}
            <option value="{{ page.id }}">{{ page.name }}</option>
        {% endfor %}
    </select>
</div>
<div>
    <label for="message">Enter the post here</label>
    <input type="text" name="message" id="message">
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

templates/accounts/add_reply.html
{% load static %}
<div class="card grow border-left-green" id='{{ id }}'>
    <div class="card-body">
        <div id="reply-words-container">
            {% for word in words %}
                {% if word != '' %}
                <div class="reply-word">
                    {{ word }}
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="card-body card-body-reply">
        {% if reply != '' %}
        <div class="reply-with">
            <img src=" {% static 'main/imgs/reply.png' %} " alt="">
            {{ reply }} 
        </div>
        {% endif %}
        {% if private_reply != '' %}
        <div class="reply-privately">
            <img src=" {% static 'main/imgs/messenger-reply.png' %} " alt="">
            {{ private_reply }}
        </div>
        {% endif %}
        <div class="reply-btns">
            <button class="btn btn-outline-primary edit">Edit</button>
            <button class="btn btn-outline-danger delete" data-bs-toggle='modal' data-bs-target='#delete-reply-modal'>Delete</button>
        </div>
    </div>
</div>

templates/accounts/base-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'main/css/profile-style.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'main/css/dashboard-style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/sidebar.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body>
  <nav class="navbar fixed-top navbar-light bg-light shadow">
    <div class="container-fluid justify-content-end">
      <a class="navbar-brand" href="#">Social Media</a>
      <ul class="nav ">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href=" {% url 'main:index' %} ">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=" {% url 'accounts:login' %} ">Logout</a>
            </li>
            <li class="nav-item">
              <i class="fas fa-bars toggler" id='toggler'></i>
            </li>
          </ul>
    </div>
  </nav>
    {% block sidebar %}{% endblock sidebar %}
    <div class="container-fluid">
                {% block content %}{% endblock content %}
        {% comment %} <div class="row">
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            </main>
    
        </div> {% endcomment %}
    </div>
    <script src=" {% static 'main/js/jquery-3.6.0.js' %} "></script>
    <script src=" {% static 'main/js/jquery-3.6.0.min.js' %} "></script>
    <script src=" {% static 'main/js/bootstrap.bundle.min.js' %} "></script>
    <script src=" {% static 'main/js/bootstrap.bundle.js' %} "></script>
    <script src=" {% static 'main/js/profile.js' %} "></script>
    <script src=" {% static 'main/js/sidebar.js' %} "></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/accounts/facebook-dashboard.html
{% extends 'accounts/base-profile.html' %}
{% load static %}
{% block title %}Facebook{% endblock title %}
{% block sidebar %}
{% include 'main/sidebar.html' with active='facebook-posts' %}
{% endblock sidebar %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/facebook-dashboard-style.css' %}">
{% endblock styles %}
{% block content %}
{% comment %} {% block name %}Facebook: {% if profile.facebook_user_name %} {{ profile.facebook_user_name }} {% endif %}{% endblock name %} {% endcomment %}
<div class="container-main">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Facebook Posts</h1>
        {% if pages %}
        <div class="btn-toolbar mb-2 mb-md-0">
            <h1 class="h5">
                {% comment %} <select name="page_id" class='form-select select' onchange='window.location.href=this.value;'> {% endcomment %}
                <select name="page_id" class='form-select select' id='page_id'>
                    {% for page in pages %}
                        <option class='form-option' value=" {{ page.id }} " {% if page_id == page.id %}selected{% endif %}>
                        {% comment %} <div><img src="{{ pic_url }}" alt="Profile Picture"></div> {% endcomment %}
                        {{ page.name }}
                        </option>
                    {% endfor %}
                </select>   
            </h1>
        </div>
        {% endif %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 ">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="card shadow-sm page border-left-blue">
                        <div class="card-body">
                            <div class="pic shadow">
                                <img src="{{ pic_url }}" alt="Profile Picture">
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div><h1 class="h5"><b>{{ page.name }}</b></h1></div>
                                    <div class='lead'>Facebook Page</div>
                                </div>
                                <div class="col-md-4 text-end">
                                    {% comment %} <a role='btn' href=" {% url 'accounts:add-post' %} " class="btn btn-primary addPost">Create Post</a> {% endcomment %}
                                    <a role='btn' href=" {% url 'accounts:add-post' %} " class="btn btn-primary addPost">Create Post</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card shadow-sm posts">
                        <div class="card-title">
                            <button class="posts-buttons buttons-active" id='published'>
                                Published
                            </button>
                            <button class="posts-buttons" id='scheduled'>
                                Scheduled
                            </button>
                            <hr>
                        </div>
                        <div class="card-body">
                            <div class="tools">
                                
                                <div class="input-group rounded">
                                        <i class="fas fa-search"></i>
                                    <input type="search" id='search' class="form-control rounded" placeholder="Search by post ID" aria-label="Search" aria-describedby="search-addon" />
                                </div>
                                <div class="lifetime">
                                    <select name="lifetime" class='form-select lifetime-select' id='lifetime'>
                                        <option class='form-option' value="lifetime">
                                            Lifetime
                                        </option>
                                        <option class='form-option' value="today">
                                            Today
                                        </option>
                                        <option class='form-option' value="yesterday">
                                            Yesterday
                                        </option>
                                        <option class='form-option' value="last7">
                                            Last 7 days 
                                        </option>
                                        <option class='form-option' value="last14">
                                            Last 14 days 
                                        </option>
                                        <option class='form-option' value="last28">
                                            Last 28 days 
                                        </option>
                                        <option class='form-option' value="thisMonth">
                                            This Month
                                        </option>
                                        <option class='form-option' value="thisYear">
                                            This Year
                                        </option>
                                    </select>   
                                </div>
                            </div>
                            <hr>
                            <div class="list-group">
                                {% for post in posts %}
                                    <a href=" {% url 'accounts:response' post.id %} " class="list-group-item list-group-item-action">
                                        {% if post.full_picture %}
                                            <div class="post-pic">
                                                <img src=" {{ post.full_picture }} " alt="full picture" class='with-pic'>
                                            </div>
                                        {% else %}
                                            <div class='non-pic post-pic'><b>Aa</b></div>
                                        {% endif %}
                                        <div class="data">
                                            <div class='table-data'> 
                                                {{ post.message|linebreaksbr }}
                                            </div>
                                        </div>
                                        <div class='form-text date'>
                                            {{ post.created_time }}
                                            {% comment %} <a href="{{ post.permalink_url }}" target='blank'>Show post on Facebook</a> {% endcomment %}
                                        </div>
                                    </a>
                                {% endfor %}
                                {% comment %} <a href="" class='more list-group-item list-group-item-secondary'>Load more posts</a> {% endcomment %}
                                {% comment %} <button class="more list-group-item list-group-item-secondary" id='loadMore' {% if not next %}style='display:none;'{% endif %}>Load more</button> {% endcomment %}
                            </div>
                        </div>
                    </div>
                {% comment %} </div> {% endcomment %}
            </div>
            <div class="col-md-4 insights stik">
                <div class="card shadow-sm info">
                    test test test
                </div>
                <div class="card border-left-green">
                    <div class="card-title">
                        <h1 class="h5"><b>Insights</b></h1>
                    </div>
                    <div class="card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque nesciunt reprehenderit consequuntur molestias assumenda vero nemo in necessitatibus asperiores? Dicta quae iure aliquam. Voluptate vel placeat, architecto eum id ut?</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas excepturi perferendis impedit magnam maxime provident necessitatibus aspernatur ipsa aliquam voluptatibus quidem vel tempore deleniti, temporibus, officia omnis id, quia magni?</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
    <script src=" {% static 'main/js/facebook-dashboard.js' %} "></script>
{% endblock scripts %}

templates/accounts/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'main/css/login-style.css' %}">
{% endblock styles %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-title mt-4 text-center">
            <h1 class="h3">Login</h1>
        </div>
        <div class="card-body text-center">
            <form action="" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success">
                            {{ message }}   
                        </div>
                    {% endfor %}
                {% endif %}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key == '__all__' %}
                            <div class="alert alert-danger">
                                {{ value }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="UsernameInput" placeholder="Email" autofocus="true" required="true" name="username">
                    <label for="UsernameInput">Email Address</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="PasswordInput" placeholder="Password" autofocus="true" required="true" name="password"> 
                    <label for="PasswordInput">Password</label>
                </div>
                <button type="submit" class="btn btn-dark mt-4">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/no-account.html
{% extends 'accounts/base-profile.html' %}
{% load static %}
{% block title %}Facebook{% endblock title %}
{% block sidebar %}
{% include 'main/sidebar.html' with active='facebook-posts' %}
{% endblock sidebar %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/facebook-profile-style.css' %}">
{% endblock styles %}
{% block content %}
{% comment %} {% block name %}Facebook: {% if profile.facebook_user_name %} {{ profile.facebook_user_name }} {% endif %}{% endblock name %} {% endcomment %}
<br><br><br>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Facebook</h1>
      </div>

        <div class="container profile ">
            <div class="card shadow-sm">
                <div class="card-body ">
                    <div class="row text-center pt-3" style='font-size: 1.3rem;'>
                        <p>
                            Please add a Facebook account to see pages here
                        </p>
                    </div>
                </div>
            </div>        
{% endblock content %}
                

templates/accounts/post.html
{% if scheduled %}1{% endif %}
<a href=" {% url 'accounts:response' post.id %} " class="list-group-item list-group-item-action">
        {% if post.full_picture %}
            <div class="post-pic">
                <img src=" {{ post.full_picture }} " alt="full picture" class='with-pic'>
            </div>
        {% else %}
            <div class='non-pic post-pic'><b>Aa</b></div>
        {% endif %}
        <div class="data">
            <div class='table-data'> 
                {{ post.message|linebreaksbr }}
            </div>
        </div>
        <div class='form-text date'>
            {{ post.created_time }}
            {% comment %} <a href="{{ post.permalink_url }}" target='blank'>Show post on Facebook</a> {% endcomment %}
        </div>
    </a>

templates/accounts/posts.html
{% for post in posts %}
    <a href=" {% url 'accounts:response' post.id %} " class="list-group-item list-group-item-action">
        {% if post.full_picture %}
            <div class="post-pic">
                <img src=" {{ post.full_picture }} " alt="full picture" class='with-pic'>
            </div>
        {% else %}
            <div class='non-pic post-pic'><b>Aa</b></div>
        {% endif %}
        <div class="data">
            <div class='table-data'> 
                {{ post.message|linebreaksbr }}
            </div>
        </div>
        <div class='form-text date'>
            {{ post.created_time }}
            {% comment %} <a href="{{ post.permalink_url }}" target='blank'>Show post on Facebook</a> {% endcomment %}
        </div>
    </a>
{% endfor %}