SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('webhooks/', include('webhooks.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from accounts.forms import RegisterForm
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    RegisterView,
    DashboardView,
    FacebookLoginView,
    FacebookProfileView,
    AddPost,
    AutomatedResponsesView,
    FacebookMorePosts,
    FacebookSearchPostsView,
    FacebookScheduledPostsView,
    FacebookLifeTimePostsView,
    FacebookPublishedPostsView,
    ReplyView,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name= 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('facebook-login/', FacebookLoginView.as_view(), name='facebook-login'),
    path('facebook/posts', FacebookProfileView.as_view(), name='facebook-profile'),
    path('facebook/more-posts', FacebookMorePosts.as_view(), name='facebook-more-posts'),
    path('facebook/scheduled-posts', FacebookScheduledPostsView.as_view(), name='facebook-scheduled-posts'),
    path('facebook/published-posts', FacebookPublishedPostsView.as_view(), name='facebook-published-posts'),
    path('facebook/posts/<str:lifetime>', FacebookLifeTimePostsView.as_view(), name = 'facebook-posts-lifetime'),
    path('add-post/', AddPost.as_view(), name='add-post'),
    path('add-automate-response/<str:post_id>/', AutomatedResponsesView.as_view(), name='response'),
    path('facebook/search-post/<str:post_id>', FacebookSearchPostsView.as_view() ,name='search-post'),
    path('facebook/post/reply', ReplyView.as_view(), name='reply'),
]

main/urls.py
from os import name
from django.urls import path
from .views import HomeView


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "main/index.html"

templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Media</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body>
    {% include 'main/navbar.html' %}
    {% block content %}{% endblock content %}
  <script src=" {% static 'main/js/bootstrap.bundle.min.js' %} "></script>
</body>
</html>

templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/aos.css' %}">
{% endblock styles %}
{% block content %}
<header class="page-header gradient">
    <div class="container pt-5">
        <div class="row align-items-center justify-content-center g-0">
            <div class="col-md-5 px-3">
                <h2>BEST PLACE TO MANAGE SOCIAL MEDIA ACCOUNTS</h2>
                <p>
                    Manage all your Social Media accounts in one place and without writing any line of code 
                </p>
            </div>
            <div class="col-md-5 text-center" data-aos='fade-up' data-aos-duration='1000'>
                <img src=" {% static 'main/imgs/Header.svg' %} " alt="Header image" style="width:24rem;">
            </div>
        </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,128L120,138.7C240,149,480,171,720,154.7C960,139,1200,85,1320,58.7L1440,32L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"></path></svg>
</header>
<section>   
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-5 " data-aos='fade-right' data-aos-duration='1000' data-aos-anchor-placement='top-center'>
                <img src=" {% static 'main/imgs/Facebook.svg' %} " alt="Facebook image" style="width:24rem;">
            </div> 
            <div class="col-md-5 p-3">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum tempora vel, eos ut quam tenetur, totam aperiam voluptate voluptas nemo illum aliquid, ullam earum iste! Itaque nostrum maiores numquam omnis.
            </div>
        </div>
    </div>
</section>
<section class="section gradient">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,256L120,229.3C240,203,480,149,720,144C960,139,1200,181,1320,202.7L1440,224L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z"></path></svg>
    <div class="container">
        <div class="row align-items-center justify-content-center p-0 m-0">
            <div class="col-md-5 p-3">
                <p>
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt itaque a nulla culpa facere quo illo praesentium minima exercitationem reiciendis tempore porro, aut consequatur numquam magnam omnis non alias? Odio!
                </p>
            </div>
            <div class="col-md-5 " data-aos='fade-up' data-aos-duration='1000' data-aos-anchor-placement='top-center'>
                <img src=" {% static 'main/imgs/Instagram.svg' %} " alt="Instagram image" style="width:23.5rem;">
            </div>
        </div>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,96L120,106.7C240,117,480,139,720,122.7C960,107,1200,53,1320,26.7L1440,0L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"></path></svg>
</section>
<section>   
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-5" data-aos='fade-right' data-aos-duration='1000' data-aos-anchor-placement='top-center'>
                <img src=" {% static 'main/imgs/Messenger001.svg' %} " alt="Messenger image" style="width:20rem;">
            </div> 
            <div class="col-md-5 p-3">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum tempora vel, eos ut quam tenetur, totam aperiam voluptate voluptas nemo illum aliquid, ullam earum iste! Itaque nostrum maiores numquam omnis.
            </div>
        </div>
    </div>
</section>
{% comment %} <footer class="bg-light text-center text-lg-start">
 
</footer> {% endcomment %}
<footer class="bg-light text-center gradient text-light">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,288L120,272C240,256,480,224,720,229.3C960,235,1200,277,1320,298.7L1440,320L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z"></path></svg>
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      >f</a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      >t</a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      >g</a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      >i</a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      >l</a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

   <!-- Copyright -->
  <div class="text-center p-3" >
    © 2021 Copyright: Made with &#10084; By  
    <a class="text-light" href="">Eng: Mohamad Daghestani</a>
  </div>
  <!-- Copyright -->
</footer>


<script src=" {% static 'main/js/aos.js' %} "></script>
<script>
    AOS.init();
</script>
{% endblock content %}

templates/main/navbar.html
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-light shadow" aria-label="Eighth navbar example">
    <div class="container">
      <a class="navbar-brand" href="#">Social Media</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarsExample07">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=" {% url 'main:index' %} ">Home</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href=" {% url 'accounts:dashboard' %} ">Welcome, {{ user.first_name }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=" {% url 'accounts:logout' %} ">Logout</a>
            </li>
            {% else %}
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'accounts:register' %} ">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'accounts:login' %} ">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/main/sidebar.html
{% comment %} <div class="sidebar-full"></div> {% endcomment %}

  <nav class='sidebar shadow expended'>
    <div class="sidebar-section">
      <div class="sidebar-section-title form-text">
        Account
      </div>
      <div class="sidebar-section-item">
        <div class="sidebar-section-item-title">
          <i class="fas fa-th" {% if active == 'dashboard' %}style='color: #0d6efd;'{% endif %}></i>
          <a href=" {% url 'accounts:dashboard' %} " {% if active == 'dashboard' %}style='color: #0d6efd;'{% endif %}>Dashboard</a>
        </div>
      </div>
      <div class="sidebar-section-item">
        <div class="sidebar-section-item-title">
          <i class="fas fa-user"></i>
          <a href="">Profile</a>
        </div>
      </div>
    </div>
    <div class="sidebar-section">
      <div class="sidebar-section-title form-text">
        Social Media
      </div>
      <div class="sidebar-section-item">
        <div class="sidebar-section-item-title {% if active == 'facebook-posts' %}active{% endif %}" id='facebook'>
          <i class="fab fa-facebook-square {% if active == 'facebook-posts' %}active{% endif %}"></i>
          Facebook
          <i class="fa fa-1x fa-chevron-right rotate {% if active == 'facebook-posts' %}down{% endif %}"></i>
        </div>
        <div class="sidebar-section-item-body" {% if active == 'facebook-posts' %}style='display: block;'{% endif %}>
          <ul>
              <li {% if active == 'facebook-posts' %}style='border-left: 2px solid #0d6efd;'{% endif %}><a href=" {% url 'accounts:facebook-profile' %} " {% if active == 'facebook-posts' %}style='color: #0d6efd;'{% endif %}>Posts</a></li>
              <li><a href="">Groups</a></li>
            </ul>
        </div>
      </div>
      <div class="sidebar-section-item">
        <div class="sidebar-section-item-title">
          <i class="fab fa-facebook-messenger"></i>
          Messenger
          <i class="fa fa-1x fa-chevron-right rotate"></i>
        </div>
        <div class="sidebar-section-item-body">
          <ul>
              <li><a href="">Posts</a></li>
              <li><a href="">Groups</a></li>
            </ul>
        </div>
      </div>
      <div class="sidebar-section-item">
        <div class="sidebar-section-item-title">
          <i class="fab fa-instagram-square"></i>
          Instagram
          <i class="fa fa-1x fa-chevron-right rotate"></i>
        </div>
        <div class="sidebar-section-item-body">
          <ul>
              <li><a href="">Posts</a></li>
              <li><a href="">Groups</a></li>
            </ul>
        </div>
      </div>
    </div>
  </nav>

templates/main/sidebar001.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse shadow navbar-collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column nav-pills" id='insert'>
                        <li id='insert-before' class="nav-item">
                            <a class="nav-link {% if active == 'dashboard' %}text-light active{% endif %}" aria-current="page" href=" {% url 'accounts:dashboard' %} ">
                            {% comment %} <span data-feather="home"></span> {% endcomment %}
                            Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            {% comment %} <a class="nav-link {% if active == 'facebook' %}text-light active{% endif %}" href=" {% url 'accounts:facebook-profile' p_id %} "> {% endcomment %}
                            <a class="nav-link {% if active == 'facebook' %}text-light active{% endif %}" href=" {% url 'accounts:facebook-profile' %} ">
                            {% comment %} <span data-feather="file"></span> {% endcomment %}
                            Facebook Pages
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="#">
                            {% comment %} <span data-feather="shopping-cart"></span> {% endcomment %}
                            Facebook Groups
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                            {% comment %} <span data-feather="users"></span> {% endcomment %}
                            Facebook Messenger
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                            {% comment %} <span data-feather="bar-chart-2"></span> {% endcomment %}
                            Instagram
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>